In [2]:
import numpy as np
import pandas as pd

In [1]:
from sentence_transformers import SentenceTransformer
import numpy as np

In [3]:
model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
anime_df=pd.read_csv('anime_clean.csv')

In [5]:
anime_df.head()

,anime_id,title,english_title,japanese_title,synopsis,type,source,episodes,status,duration,...,members,favorites,rank,popularity,genres,themes,demographics,studios,tags,text_for_embedding
0,1.0,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,"Crime is timeless. By the year 2071, humanity ...",TV,Original,26.0,Finished Airing,24 min per ep,...,2033582.0,88901.0,47.0,42.0,"['Action', 'Award Winning', 'Sci-Fi']","['Adult Cast', 'Space']",[],['Sunrise'],Action Award Winning Sci-Fi Adult Cast Space,"Crime is timeless. By the year 2071, humanity ..."
1,6.0,Trigun,Trigun,トライガン,"Vash the Stampede is the man with a $$60,000,0...",TV,Manga,26.0,Finished Airing,24 min per ep,...,825583.0,17438.0,408.0,265.0,"['Action', 'Adventure', 'Sci-Fi']",['Adult Cast'],['Shounen'],['Madhouse'],Action Adventure Sci-Fi Adult Cast Shounen,"Vash the Stampede is the man with a $$60,000,0..."
2,7.0,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),"Though hidden away from the general public, Wi...",TV,Original,26.0,Finished Airing,25 min per ep,...,127702.0,694.0,3418.0,1984.0,"['Action', 'Drama', 'Mystery', 'Supernatural']",['Detective'],[],['Sunrise'],Action Drama Mystery Supernatural Detective,"Though hidden away from the general public, Wi..."
3,8.0,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,It is the dark century and the people are suff...,TV,Manga,52.0,Finished Airing,23 min per ep,...,16589.0,18.0,4909.0,5843.0,"['Action', 'Adventure', 'Fantasy']",[],['Shounen'],['Toei Animation'],Action Adventure Fantasy Shounen,It is the dark century and the people are suff...
4,15.0,Eyeshield 21,NaN,アイシールド21,"Shy, reserved, and small-statured, Deimon High...",TV,Manga,145.0,Finished Airing,23 min per ep,...,194861.0,2108.0,862.0,1406.0,['Sports'],['Team Sports'],['Shounen'],['Gallop'],Sports Team Sports Shounen,"Shy, reserved, and small-statured, Deimon High..."

In [43]:
anime_df[anime_df['title'].str.contains('Shingeki')]

,anime_id,title,english_title,japanese_title,synopsis,type,source,episodes,status,duration,...,members,favorites,rank,popularity,genres,themes,demographics,studios,tags,text_for_embedding
5234,16498.0,Shingeki no Kyojin,Attack on Titan,進撃の巨人,"Centuries ago, mankind was slaughtered to near...",TV,Manga,25.0,Finished Airing,24 min per ep,...,4306276.0,186870.0,117.0,1.0,"['Action', 'Award Winning', 'Drama', 'Suspense']","['Gore', 'Military', 'Survival']",['Shounen'],['Wit Studio'],Action Award Winning Drama Suspense Gore Milit...,"Centuries ago, mankind was slaughtered to near..."
5455,18397.0,Shingeki no Kyojin OVA,Attack on Titan OAD,進撃の巨人ＯＡＤ,Ilse no Techou: Aru Chousa Heidanin no Shuki\n...,OVA,Manga,3.0,Finished Airing,24 min per ep,...,502482.0,1005.0,915.0,505.0,"['Action', 'Drama', 'Suspense']","['Gore', 'Survival']",['Shounen'],['Wit Studio'],Action Drama Suspense Gore Survival Shounen,Ilse no Techou: Aru Chousa Heidanin no Shuki\n...
5550,19391.0,Shingeki no Kyojin Picture Drama,"Attack on Titan: Chibi Theater - Fly, Cadets, ...","「進撃の巨人」ちみキャラ劇場""とんでけ! 訓練兵団""",Shingeki no Kyojin Picture Drama is a series ...,Special,Manga,9.0,Finished Airing,10 min per ep,...,59873.0,77.0,6692.0,3199.0,['Comedy'],['Parody'],[],['Studio Moriken'],Comedy Parody,Shingeki no Kyojin Picture Drama is a series ...
5805,21843.0,Shingeki no Bahamut: Genesis,Rage of Bahamut: Genesis,神撃のバハムート GENESIS,"Thousands of years ago, the ancient dragon Bah...",TV,Card game,12.0,Finished Airing,24 min per ep,...,436270.0,1717.0,1633.0,600.0,"['Action', 'Adventure', 'Fantasy']",[],[],['MAPPA'],Action Adventure Fantasy,"Thousands of years ago, the ancient dragon Bah..."
6230,25777.0,Shingeki no Kyojin Season 2,Attack on Titan Season 2,進撃の巨人 Season2,"For centuries, humanity has been hunted by gia...",TV,Manga,12.0,Finished Airing,24 min per ep,...,2982003.0,22911.0,136.0,12.0,"['Action', 'Drama', 'Suspense']","['Gore', 'Military', 'Survival']",['Shounen'],['Wit Studio'],Action Drama Suspense Gore Military Survival S...,"For centuries, humanity has been hunted by gia..."
6231,25781.0,Shingeki no Kyojin: Kuinaki Sentaku,Attack on Titan: No Regrets,進撃の巨人 悔いなき選択,Many years before becoming the famed captain o...,OVA,Visual novel,2.0,Finished Airing,27 min per ep,...,559469.0,2032.0,208.0,439.0,['Action'],[],[],['Wit Studio'],Action,Many years before becoming the famed captain o...
6855,30736.0,Shingeki no Bahamut: Virgin Soul,Rage of Bahamut: Virgin Soul,神撃のバハムート VIRGIN SOUL,"A decade ago, humans, gods, and demons joined ...",TV,Card game,24.0,Finished Airing,24 min per ep,...,258119.0,1073.0,2396.0,1072.0,"['Action', 'Adventure', 'Fantasy']",[],[],['MAPPA'],Action Adventure Fantasy,"A decade ago, humans, gods, and demons joined ..."
7016,31374.0,Shingeki! Kyojin Chuugakkou,Attack on Titan: Junior High,進撃！巨人中学校,"On his first day of junior high, Eren Yeager c...",TV,Manga,12.0,Finished Airing,17 min per ep,...,284932.0,855.0,3422.0,973.0,['Comedy'],"['Parody', 'School']",['Shounen'],['Production I.G'],Comedy Parody School Shounen,"On his first day of junior high, Eren Yeager c..."
7882,34642.0,Shingeki no Bahamut: Genesis - Short Story,Rage of Bahamut: Genesis - Short Story,【神撃のバハムート GENESIS】 Short story,The first short story focuses on Favaro and Ka...,ONA,Game,2.0,Finished Airing,9 min per ep,...,30315.0,11.0,3930.0,4577.0,"['Action', 'Adventure', 'Fantasy']",[],[],['MAPPA'],Action Adventure Fantasy,The first short story focuses on Favaro and Ka...
8056,35122.0,Shingeki no Kyotou,Attack on Skytree,進撃の巨塔,A special anime featuring a battle against the...,Movie,Manga,1.0,Finished Airing,7 min,...,27384.0,88.0,8216.0,4799.0,"['Action', 'Fantasy']",[],['Shounen'],[],Action Fantasy Shounen,A special anime featuring a battle against the...
8272,35760.0,Shingeki no Kyojin Season 3,Attack on Titan Season 3,進撃の巨人 Season3,"Still threatened by the ""Titans"" that rob them...",TV,Manga,12.0,Finished Airing,23 min per ep,...,2628267.0,22208.0,85.0,18.0,"['Action', 'Drama', 'Suspense']","['Gore', 'Military', 'Survival']",['Shounen'],['Wit Studio'],Action Drama Suspense Gore Military Survival S...,"Still threatened by the ""Titans"" that rob them..."
8351,36106.0,Shingeki no Kyojin: Lost Girls,Attack on Titan: Lost Girls,進撃の巨人 LOST GIRLS,"Wall Sina, Goodbye\nAnnie Leonhart has a job t...",OVA,Novel,3.0,Finished Airing,25 min per ep,...,335256.0,591.0,1048.0,817.0,"['Action', 'Drama']",[],[],['Wit Studio'],Action Drama,"Wall Sina, Goodbye\nAnnie Leonhart has a job t..."
8521,36702.0,Shingeki no Kyojin Season 2 Movie: Kakusei no ...,Attack on Titan: The Roar of Awakening,劇場版 進撃の巨人 Season2〜覚醒の咆哮〜,Eren Yeager and others of the 104th Training C...,Movie,Manga,1.0,Finished Airing,2 hr,...,83358.0,104.0,755.0,2639.0,"['Action', 'Drama', 'Suspense']","['Gore', 'Survival']",['Shounen'],['Wit Studio'],Action Drama Suspense Gore Survival Shounen,Eren Yeager and others of the 104th Training C...
9138,38524.0,Shingeki no Kyojin Season 3 Part 2,Attack on Titan Season 3 Part 2,進撃の巨人 Season3 Part.2,Seeking to restore humanity's diminishing hope...,TV,Manga,10.0,Finished Airing,23 min per ep,...,2552878.0,62680.0,6.0,20.0,"['Action', 'Drama', 'Suspense']","['Gore', 'Military', 'Survival']",['Shounen'],['Wit Studio'],Action Drama Suspense Gore Military Survival S...,Seeking to restore humanity's diminishing hope...
9455,39477.0,Shingeki no Kyojin Season 3 Specials,"Attack on Titan: Chibi Theater - Survey Corps,...",｢進撃の巨人｣ちみキャラ劇場”とんでけ！新生リヴァイ班”,Shingeki no Kyojin Season 3 DVD/BD specials. T...,Special,Manga,7.0,Finished Airing,2 min per ep,...,43223.0,82.0,1487.0,3861.0,['Comedy'],['Parody'],['Shounen'],['Studio Moriken'],Comedy Parody Shounen,Shingeki no Kyojin Season 3 DVD/BD specials. T...
9456,39478.0,Shingeki no Kyojin in the Dome: Heishi-tachi n...,Attack on Titan in the Dome: Soldiers' Starry Sky,進撃の巨人 IN THE DOME -兵士たちの星空-,A planetarium film screened originally at the ...,Movie,Manga,1.0,Finished Airing,20 min,...,23881.0,36.0,2492.0,5065.0,[],"['Military', 'Space']",['Shounen'],[],Military Space Shounen,A planetarium film screened originally at the ...
9603,40028.0,Shingeki no Kyojin: The Final Season,Attack on Titan: Final Season,進撃の巨人 The Final Season,Gabi Braun and Falco Grice have been training ...,TV,Manga,16.0,Finished Airing,23 min per ep,...,2253624.0,53863.0,38.0,30.0,"['Action', 'Drama', 'Suspense']","['Gore', 'Military', 'Survival']",['Shounen'],['MAPPA'],Action Drama Suspense Gore Military Survival S...,Gabi Braun and Falco Grice have been training ...
10631,48583.0,Shingeki no Kyojin: The Final Season Part 2,Attack on Titan: Final Season Part 2,進撃の巨人 The Final Season Part 2,Turning against his former allies and enemies ...,TV,Manga,12.0,Finished Airing,23 min per ep,...,1528489.0,32136.0,44.0,92.0,"['Action', 'Drama', 'Suspense']","['Gore', 'Military', 'Survival']",['Shounen'],['MAPPA'],Action Drama Suspense Gore Military Survival S...,Turning against his former allies and enemies ...
10841,49627.0,Shingeki no Kyojin: The Final Season Specials,"Attack on Titan: Chibi Theater - Survey Corps,...",進撃の巨人 The Final Season Specials,Shingeki no Kyojin Season 4 DVD/BD specials. T...,Special,Manga,2.0,Finished Airing,5 min per ep,...,19733.0,114.0,1407.0,5475.0,['Comedy'],['Parody'],[],['Studio Moriken'],Comedy Parody,Shingeki no Kyojin Season 4 DVD/BD specials. T...
11235,51535.0,Shingeki no Kyojin: The Final Season - Kankets...,Attack on Titan: Final Season - The Final Chap...,進撃の巨人 The Final Season完結編,In the wake of Eren Yeager's cataclysmic actio...,TV Special,Manga,2.0,Finished Airing,1 hr 12 min per ep,...,841125.0,17179.0,28.0,256.0,"['Action', 'Drama', 'Suspense']","['Gore', 'Military', 'Survival']",['Shounen'],['MAPPA'],Action Drama Suspense Gore Military Survival S...,In the wake of Eren Yeager's cataclysmic actio...

In [6]:
embeddings = model.encode(anime_df['text_for_embedding'].tolist(),show_progress_bar=True)

Batches:   0%|          | 0/426 [00:00<?, ?it/s]

In [7]:
np.save('anime_embeddings.npy',embeddings)

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
import os
os.makedirs('/content/drive/MyDrive/anime_project', exist_ok=True)
np.save('/content/drive/MyDrive/anime_project/anime_embeddings.npy', embeddings)

CHECKING

In [13]:
print(embeddings.shape)

(13612, 384)

In [14]:
print(np.isnan(embeddings).any())
print(np.all(embeddings == 0, axis=1).sum())

False
0

In [42]:
from sentence_transformers import util

query_idx = anime_df[anime_df['title'] == "Death Note" ].index[0]
query_embedding = embeddings[query_idx]

similarities = util.cos_sim(query_embedding, embeddings)[0]
top_indices = similarities.argsort(descending=True)[1:6]  # top 5 excluding itself

for idx in top_indices:
    print(anime_df.iloc[idx.item()]['title'], '-', round(float(similarities[idx]), 3))

Death Note: Rewrite - 0.848
ChäoS;HEAd - 0.598
Angel Beats! - 0.594
Ankoku Shinwa - 0.575
Shin Megami Tensei: Tokyo Mokushiroku - 0.574

In [44]:
from difflib import SequenceMatcher

def get_recommendations(title, n=5):
    query_row = anime_df[anime_df['title'].str.contains(title, case=False)].iloc[0]
    query_idx = query_row.name
    query_embedding = embeddings[query_idx]
    query_title = query_row['title']

    similarities = util.cos_sim(query_embedding, embeddings)[0]
    top_indices = similarities.argsort(descending=True)[1:]  # exclude itself

    results = []
    for idx in top_indices:
        idx = idx.item()
        candidate_title = anime_df.iloc[idx]['title']
        similarity_score = float(similarities[idx])

        query_root = query_title.lower().split(':')[0].strip()
        candidate_root = candidate_title.lower().split(':')[0].strip()
        if query_root in candidate_title.lower() or candidate_root in query_title.lower():
            continue

        ratio = SequenceMatcher(None, query_title.lower(), candidate_title.lower()).ratio()
        if ratio > 0.6:
            continue

        results.append({
            'title': candidate_title,
            'similarity': round(similarity_score, 3)
        })

        if len(results) == n:
            break

    return results

In [47]:
get_recommendations('Gintama')

[{'title': 'Karakuri no Kimi', 'similarity': 0.659},
 {'title': 'Hakuouki: Reimeiroku', 'similarity': 0.652},
 {'title': 'Kamishibai Kintarou no Maki', 'similarity': 0.647},
 {'title': 'Kaitouranma The Animation', 'similarity': 0.642},
 {'title': 'Shouwa Genroku Rakugo Shinjuu', 'similarity': 0.629}]